// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdq86gHeCeSB6J02tHgtdyT7Eh_9mdg-Y',
    appId: '1:443744463685:web:f2544bcf48b64154e6ec2c',
    messagingSenderId: '443744463685',
    projectId: 'instagram-app-1c120',
    authDomain: 'instagram-app-1c120.firebaseapp.com',
    storageBucket: 'instagram-app-1c120.appspot.com',
    measurementId: 'G-HT77J53HGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWulK5PX_6i5xd9aPBconnTLE8fYrqqd8',
    appId: '1:443744463685:android:8882a38bdbdb6e41e6ec2c',
    messagingSenderId: '443744463685',
    projectId: 'instagram-app-1c120',
    storageBucket: 'instagram-app-1c120.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATw7IP2ahWW703C5C3I35kIrlGozwBn2I',
    appId: '1:443744463685:ios:fb83bfdc3d663e77e6ec2c',
    messagingSenderId: '443744463685',
    projectId: 'instagram-app-1c120',
    storageBucket: 'instagram-app-1c120.appspot.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATw7IP2ahWW703C5C3I35kIrlGozwBn2I',
    appId: '1:443744463685:ios:fb83bfdc3d663e77e6ec2c',
    messagingSenderId: '443744463685',
    projectId: 'instagram-app-1c120',
    storageBucket: 'instagram-app-1c120.appspot.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdq86gHeCeSB6J02tHgtdyT7Eh_9mdg-Y',
    appId: '1:443744463685:web:9868f7f2c6d66593e6ec2c',
    messagingSenderId: '443744463685',
    projectId: 'instagram-app-1c120',
    authDomain: 'instagram-app-1c120.firebaseapp.com',
    storageBucket: 'instagram-app-1c120.appspot.com',
    measurementId: 'G-XJ1MSK4ZRF',
  );

}